spring:
  profiles:
    active: local

#server:
#  port: 8090

config:
  api:
    baseUrl: https://apiv2.apifootball.com/
    key: 9bb66184e0c8145384fd2cc0f7b914ada57b4e8fd2e4d6d586adcc27c257a978
    action:
      countries: get_countries
      leagues: get_leagues
      standings: get_standings

